# Generated by Django 5.1.3 on 2024-11-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qera', '0014_car_description_car_fuel_type_car_mileage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
