# Generated by Django 5.1.3 on 2024-12-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qera', '0015_reservation_email_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='rental_price',
            new_name='winter_rental_price',
        ),
        migrations.AddField(
            model_name='car',
            name='summer_rental_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
